# Generated by Django 5.2.17 on 2026-09-18 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
