# Generated by Django 5.2.17 on 2026-09-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
