# Generated by Django 5.2.17 on 2026-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
    ]
