# Generated by Django 5.2.17 on 2026-09-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_rename_user_id_to_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="user_id",
            new_name="user",
        ),
    ]