# Generated by Django 5.2.17 on 2026-09-19 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0003_rename_user_id_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', related_query_name='workout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rest_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', related_query_name='workout_exercise', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', related_query_name='workout_exercise', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'WorkoutExercise',
                'verbose_name_plural': 'WorkoutExercises',
                'db_table': 'WorkoutExercise',
                'ordering': ['workout', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', related_query_name='workout', through='workouts.WorkoutExercise', to='exercises.exercise'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_workout_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='unique_order_per_workout'),
        ),
    ]
