# Generated by Django 5.2.17 on 2026-09-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_description_alter_workout_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Canacelled'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(verbose_name=120)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_sessions', related_query_name='workout_session', to='workouts.workout', unique=True)),
            ],
            options={
                'verbose_name': 'WorkoutSessions',
                'verbose_name_plural': 'WorkoutSession',
                'db_table': 'WorkoutSession',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
