# Generated by Django 5.2.17 on 2026-09-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_sessions', related_query_name='workout_session', to='workouts.workout'),
        ),
    ]
