# Generated by Django 5.2.17 on 2026-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workoutsession_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
