# Generated by Django 5.2.17 on 2026-09-20 16:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0007_workoutexercise_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps_completed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.DurationField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('weight_completed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=120)),
                ('exercise_order', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ['workout_session', 'exercise_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Workout session', 'verbose_name_plural': 'Workout sessions'},
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='total_duration',
            field=models.DurationField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise'), name='unique_exercise_per_workout'),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='exercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_results', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_results', related_query_name='exercise_result', to='workouts.workoutexercise'),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_results', related_query_name='exercise_result', to='workouts.workoutsession'),
        ),
        migrations.AddConstraint(
            model_name='exerciseresult',
            constraint=models.UniqueConstraint(fields=('workout_session', 'workout_exercise'), name='unique_exercise_result_per_session'),
        ),
    ]
