# Generated by Django 5.2.17 on 2026-09-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_exerciseresult_alter_workoutsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseresult',
            name='note',
        ),
    ]
